[web]
bind_address = "127.0.0.1:3030"
# external_address = "http://www.example.com"
backend = "in_memory"

[project_service]
list_limit = 20

[dataset_service]
list_limit = 20

[postgres]
config_string = "postgresql://geoengine:geoengine@localhost:5432"

[operators.gdal_source]
raster_data_root_path = "data"

[raster.tiling_specification]
origin_coordinate_x = 0.0
origin_coordinate_y = 0.0
tile_shape_pixels_x = 600
tile_shape_pixels_y = 600

[query_context]
chunk_byte_size = 1048576 # TODO: find reasonable default
